version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dev-justbardtech-sam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-vfpf1w76svod"
s3_prefix = "dev-justbardtech-sam"
region = "us-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ProjectName=\"justbardtech\" ProjectNameUpper=\"JustBardTech\" EnvironmentName=\"dev\" EnvironmentNameUpper=\"Dev\" EnvironmentStage=\"Dev\" SLACKWEBHOOKURL=\"\" SlackErrorHookURL=\"\" SLACKCHANNEL=\"\" SLACKVERIFICATIONTOKEN=\"zld8LpUs03wC7BiASyjULU4k\""

